language: go

# Only clone the most recent commit.
git:
  depth: 1

notifications:
  email: false

go:
- master #latest

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/golang/mock/mockgen

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
- go generate ./...
- go test -coverprofile c.out ./...
- $GOPATH/bin/goveralls -service=travis-ci

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT